URL_HOME_PAGE = 'https://stellarburgers.nomoreparties.site/'
URL_LOGIN_PAGE = 'https://stellarburgers.nomoreparties.site/login'
URL_FORGOT_PASSWORD = 'https://stellarburgers.nomoreparties.site/forgot-password'
URL_RESET_PASSWORD = 'https://stellarburgers.nomoreparties.site/reset-password'
URL_ACCOUNT_PROFILE = 'https://stellarburgers.nomoreparties.site/account/profile'
URL_ORDER_HISTORY = 'https://stellarburgers.nomoreparties.site/account/order-history'
URL_ORDERS_FEED = 'https://stellarburgers.nomoreparties.site/feed'
URL_REGISTER = 'https://stellarburgers.nomoreparties.site/api/auth/register'
